##################################
# general parameters
##################################
general:
  data_file: '/root/projects/aortic_dissection/data_files/train/CTA_AO.csv'
  val_list: '/root/projects/aortic_dissection/data_files/train/sub10_CTA_AO.csv'
  save_dir: '/root/projects/aortic_dissection/models/autodl_debug/'
  load_dir: ''
  resume_epoch: -1
  clear_start_epoch: false
  num_gpus: 2
  seed: 0
  partial: false


#####################################
# net
#####################################
net:
  name: 'vnet'
  use_ds: false
  bn_sync: false


##################################
# data set parameters
##################################
dataset:
  num_modality: 1
  # 2 for binary segmentation
  num_classes: 2
  # target resample spacing during preprocess
  spacing: [1, 1, 1]
  crop_size: [128, 128, 256]
  aug_config:
    aug_prob: 0.5
    shift_config:
      shift_prob: 1
      shift_mm: 10
    rot_config:
      rot_prob: 0.5
      rot_angle_degree: 180
      rot_axis: [[0, 0, 1]] # x y z
    flip_config:
      flip_x_prob: 0
      flip_y_prob: 0
      flip_z_prob: 0
    scale_config:
      scale_prob: 0.5
      scale_min_ratio: 0.9
      scale_max_ratio: 1.1
      scale_isotropic: false
    cover_config:
      cover_prob: 0
      cover_ratio: 0.4
      mu_value: 20
      sigma_value: 50
    truncate_config:
      trunc_bottom_prob: 0
      trunc_top_prob: 0
      trunc_ratio_range: [0.2, 0.5]
    brightness_config:
      brightness_prob: 0
      mul_range: [0.8, 1.2]
    contrast_config:
      contrast_prob: 0
      contrast_range: [0.75, 1.25]
    gamma_contrast_config:
      gamma_contrast_prob: 0.0
      gamma_range: [0.7, 1.5]
    gaussian_noise_config:
      gaussian_noise_prob: 0.0
      noise_scale: [0, 51.2] # 0.05 * 1024
    gaussian_blur_config:
      gaussian_blur_prob: 0
      sigma_range: [0.5, 1.5]
    simulatelowres_config:
      simulatelowres_prob: 0
      zoom_range: [0.5, 1]
  pad_t: 0
  default_values: [-1024, 0, 0]
  # sampling_method: 'MASK'
  # mixed_rate: 0.5
  box_sample_padding: [0, 0, 0, 0, 0, 0]
  interpolation: 'NN'
  crop_normalizers:
    mean: 300
    std: 400


####################################
# training loss
####################################
loss:
  name: 'DiceLoss'
  double_loss_weight: [0.5, 0.5]
  obj_weight: [1, 1]
  focal_gamma: 2
  # parameters for BoundaryLoss,k=min(epoch_idx / k_slope + 0.01, k_max)
  k_slope: 700
  k_max: 0.2
  level: 20
  dim: 3
  # parameters for cldice loss
  cldice_iter: 15
  smooth: !!float 1e-6 
  # weight for regular term MEEP
  reg_w: 0.5


######################################
# training parameters
######################################
train:
  epochs: 701
  batchsize: 4
  num_threads: 5
  lr: !!float 1e-3
  lr_scheduler:
    name: "MultiStepLR"
    params:
      milestones: [120, 200, 350]
      gamma: 0.1
      last_epoch: -1
  optimizer:
    name: "Adam"
    params:
      betas: [0.9, 0.999]
      eps: !!float 1e-8
      weight_decay: 0
      amsgrad: false
  plot_snapshot: 100
  save_epochs: 10
  val_epoch: 10

debug:
  # whether to save input crops
  save_inputs: false